services:
  grafana:
    container_name: 'weathermap-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/weathermap-panel
      - ./provisioning:/etc/grafana/provisioning
